config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/search',  to: 'searches#search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:create, :destroy, :show, :new]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p class="copyright">&copy; 2022 Ritsuki hayashi</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark">
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <%= link_to "travel board", root_path, id: "logo" %>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %>
        <li class="nav-item">
          <%= form_with url: search_path, local: true, class: "search_form", method: :get do |f| %>
            <%= f.text_field :word, placeholder: "Search", value: params[:word], class: "col-md-7 search_text" %>
            <%= f.select :range, options_for_select([['User'], ['Post']], selected: params[:range]), {}, {class: "col-md-4"} %>
            <%= button_tag type: "submit", class: "btn btn-default search_btn col-md-1" do %>
            <i class="fa-solid fa-magnifying-glass"></i>
            <% end %>
          <% end %>
        </li>
      <% end %>
      <li class="nav-item active"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Profile", current_user, class: "dropdown-item" %>
            <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%= link_to "Log in", login_path, class: "nav-link" %>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://kit.fontawesome.com/633820dfa7.js" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>
<script async
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&libraries=places&callback=initMap&language=ja">
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main class="container d-flex justify-content-center align-items-center">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <!--<%= debug(params) if Rails.env.development? %>-->
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

<script type="text/javascript">
  function initMap() {};
</script>